// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: go-vroom/v1/solve.proto

package v1

import (
	context "context"
	request "go-vroom/api/go-vroom/v1/request"
	response "go-vroom/api/go-vroom/v1/response"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Solve_Solve_FullMethodName = "/go_vroom.v1.Solve/Solve"
)

// SolveClient is the client API for Solve service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SolveClient interface {
	Solve(ctx context.Context, in *request.SolveRequest, opts ...grpc.CallOption) (*response.SolveResponse, error)
}

type solveClient struct {
	cc grpc.ClientConnInterface
}

func NewSolveClient(cc grpc.ClientConnInterface) SolveClient {
	return &solveClient{cc}
}

func (c *solveClient) Solve(ctx context.Context, in *request.SolveRequest, opts ...grpc.CallOption) (*response.SolveResponse, error) {
	out := new(response.SolveResponse)
	err := c.cc.Invoke(ctx, Solve_Solve_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SolveServer is the server API for Solve service.
// All implementations must embed UnimplementedSolveServer
// for forward compatibility
type SolveServer interface {
	Solve(context.Context, *request.SolveRequest) (*response.SolveResponse, error)
	mustEmbedUnimplementedSolveServer()
}

// UnimplementedSolveServer must be embedded to have forward compatible implementations.
type UnimplementedSolveServer struct {
}

func (UnimplementedSolveServer) Solve(context.Context, *request.SolveRequest) (*response.SolveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Solve not implemented")
}
func (UnimplementedSolveServer) mustEmbedUnimplementedSolveServer() {}

// UnsafeSolveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SolveServer will
// result in compilation errors.
type UnsafeSolveServer interface {
	mustEmbedUnimplementedSolveServer()
}

func RegisterSolveServer(s grpc.ServiceRegistrar, srv SolveServer) {
	s.RegisterService(&Solve_ServiceDesc, srv)
}

func _Solve_Solve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(request.SolveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SolveServer).Solve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Solve_Solve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SolveServer).Solve(ctx, req.(*request.SolveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Solve_ServiceDesc is the grpc.ServiceDesc for Solve service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Solve_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go_vroom.v1.Solve",
	HandlerType: (*SolveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Solve",
			Handler:    _Solve_Solve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go-vroom/v1/solve.proto",
}
