// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: go-vroom/v1/types/break.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Break struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          uint64        `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Description string        `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Service     uint32        `protobuf:"varint,3,opt,name=service,proto3" json:"service,omitempty"`
	TimeWindows []*TimeWindow `protobuf:"bytes,4,rep,name=time_windows,json=timeWindows,proto3" json:"time_windows,omitempty"`
	MaxLoad     []uint32      `protobuf:"varint,5,rep,packed,name=max_load,json=maxLoad,proto3" json:"max_load,omitempty"`
}

func (x *Break) Reset() {
	*x = Break{}
	if protoimpl.UnsafeEnabled {
		mi := &file_go_vroom_v1_types_break_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Break) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Break) ProtoMessage() {}

func (x *Break) ProtoReflect() protoreflect.Message {
	mi := &file_go_vroom_v1_types_break_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Break.ProtoReflect.Descriptor instead.
func (*Break) Descriptor() ([]byte, []int) {
	return file_go_vroom_v1_types_break_proto_rawDescGZIP(), []int{0}
}

func (x *Break) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Break) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Break) GetService() uint32 {
	if x != nil {
		return x.Service
	}
	return 0
}

func (x *Break) GetTimeWindows() []*TimeWindow {
	if x != nil {
		return x.TimeWindows
	}
	return nil
}

func (x *Break) GetMaxLoad() []uint32 {
	if x != nil {
		return x.MaxLoad
	}
	return nil
}

var File_go_vroom_v1_types_break_proto protoreflect.FileDescriptor

var file_go_vroom_v1_types_break_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x67, 0x6f, 0x2d, 0x76, 0x72, 0x6f, 0x6f, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x62, 0x72, 0x65, 0x61, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x11, 0x67, 0x6f, 0x5f, 0x76, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x1a, 0x23, 0x67, 0x6f, 0x2d, 0x76, 0x72, 0x6f, 0x6f, 0x6d, 0x2f, 0x76, 0x31, 0x2f,
	0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f,
	0x77, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb0, 0x01, 0x0a, 0x05, 0x42, 0x72, 0x65, 0x61,
	0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x40, 0x0a,
	0x0c, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x77, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x18, 0x04, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x67, 0x6f, 0x5f, 0x76, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x76,
	0x31, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x57, 0x69, 0x6e, 0x64,
	0x6f, 0x77, 0x52, 0x0b, 0x74, 0x69, 0x6d, 0x65, 0x57, 0x69, 0x6e, 0x64, 0x6f, 0x77, 0x73, 0x12,
	0x19, 0x0a, 0x08, 0x6d, 0x61, 0x78, 0x5f, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x05, 0x20, 0x03, 0x28,
	0x0d, 0x52, 0x07, 0x6d, 0x61, 0x78, 0x4c, 0x6f, 0x61, 0x64, 0x42, 0x4a, 0x0a, 0x11, 0x67, 0x6f,
	0x2d, 0x76, 0x72, 0x6f, 0x6f, 0x6d, 0x2e, 0x76, 0x31, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x50,
	0x01, 0x5a, 0x24, 0x67, 0x6f, 0x2d, 0x76, 0x72, 0x6f, 0x6f, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x2f,
	0x67, 0x6f, 0x2d, 0x76, 0x72, 0x6f, 0x6f, 0x6d, 0x2f, 0x76, 0x31, 0x2f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x3b, 0x74, 0x79, 0x70, 0x65, 0x73, 0xa2, 0x02, 0x0c, 0x41, 0x50, 0x49, 0x47, 0x6f, 0x56,
	0x72, 0x6f, 0x6f, 0x6d, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_go_vroom_v1_types_break_proto_rawDescOnce sync.Once
	file_go_vroom_v1_types_break_proto_rawDescData = file_go_vroom_v1_types_break_proto_rawDesc
)

func file_go_vroom_v1_types_break_proto_rawDescGZIP() []byte {
	file_go_vroom_v1_types_break_proto_rawDescOnce.Do(func() {
		file_go_vroom_v1_types_break_proto_rawDescData = protoimpl.X.CompressGZIP(file_go_vroom_v1_types_break_proto_rawDescData)
	})
	return file_go_vroom_v1_types_break_proto_rawDescData
}

var file_go_vroom_v1_types_break_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_go_vroom_v1_types_break_proto_goTypes = []interface{}{
	(*Break)(nil),      // 0: go_vroom.v1.types.Break
	(*TimeWindow)(nil), // 1: go_vroom.v1.types.TimeWindow
}
var file_go_vroom_v1_types_break_proto_depIdxs = []int32{
	1, // 0: go_vroom.v1.types.Break.time_windows:type_name -> go_vroom.v1.types.TimeWindow
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_go_vroom_v1_types_break_proto_init() }
func file_go_vroom_v1_types_break_proto_init() {
	if File_go_vroom_v1_types_break_proto != nil {
		return
	}
	file_go_vroom_v1_types_time_window_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_go_vroom_v1_types_break_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Break); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_go_vroom_v1_types_break_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_go_vroom_v1_types_break_proto_goTypes,
		DependencyIndexes: file_go_vroom_v1_types_break_proto_depIdxs,
		MessageInfos:      file_go_vroom_v1_types_break_proto_msgTypes,
	}.Build()
	File_go_vroom_v1_types_break_proto = out.File
	file_go_vroom_v1_types_break_proto_rawDesc = nil
	file_go_vroom_v1_types_break_proto_goTypes = nil
	file_go_vroom_v1_types_break_proto_depIdxs = nil
}
